services:
  - type: web
    name: ecommerce-backend
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-db.onrender.com:3306/ecommerce_project?allowPublicKeyRetrieval=true&useSSL=false
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: 21121Aa3316@
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: mysql-db
    databaseName: ecommerce_project
    user: root
    plan: free
